portfolio/blueprints/page/__init__.py
from portfolio.blueprints.page.views import page

portfolio/blueprints/page/views.py
from flask import Blueprint, render_template, redirect, url_for

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/', methods=['GET','POST'])
def home():
    return render_template('page/home.html')

@page.route('/contact', methods=['GET','POST'])
def contact():
    return render_template('page/contact.html')

@page.route('/ecom_project', methods=['GET','POST'])
def ecom_project():
    return render_template('page/ecom_project.html')

portfolio/blueprints/page/templates/page/contact.html
{% extends 'layouts/base.html' %}

{% block body %}
<p class="text-center">
  Thank you, your message has been succesfully sent!
</p>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

portfolio/blueprints/page/templates/page/ecom_project.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Malick Gueye - Resume & Blog & Projects</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">

  <!-- Favicons -->
  

  <!-- Vendor CSS Files -->
  <link 
    rel="stylesheet"
    href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}">
  <link 
    rel="stylesheet"
    href="{{ url_for('static', filename='vendor/font-awesome/css/font-awesome.min.css') }}" >
  <link
    rel="stylesheet" 
    href="{{ url_for('static', filename='vendor/ionicons/css/ionicons.min.css') }}" >



  <!-- Template Main CSS File -->
  <link 
    rel="stylesheet"
    href="{{ url_for('static', filename='css/app.css') }}" >

  <!-- =======================================================
  * Template Name: DevFolio - v2.4.0
  * Template URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body id="page-top">


  <!-- ======= Header/ Navbar ======= -->
  <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll" href="#page-top">Malick Gueye</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll active" href="{{url_for('page.home')}}">Home</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>

 

  <main id="main">
  <br>
  <br>
    <!-- ======= Blog Single Section ======= -->
    <section class="blog-wrapper sect-pt4" id="blog">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="post-box">
              <div class="post-thumb">
                <img src="assets/img/post-1.jpg" class="img-fluid" alt="">
              </div>
              <div class="post-meta">
                <h1 class="article-title">Architecture of the application</h1>
                This post details our ecommerce application factory. A description of all the tools used and why we use them from development to launching our site in a secure server.
                <ul>
                  <li>
                    <a href="#flask" class="text-secondary">Flask</a>
                  </li>
                  <li>
                    <a href="#database" class="text-secondary">Database Design</a>
                  </li>
                  <li>
                    <a href="#docker" class="text-secondary">Docker and Docker-compose</a>
                  </li>
                  <li>
                    <a href="#extensions" class="text-secondary">Flask Extensions</a>
                  </li>
                  <li>
                    <a href="#linode" class="text-secondary">Linode server configuration</a>
                  </li>
                </ul>
              </div>
              <div class="article-content">
                <blockquote class="blockquoteb text-primary">
                  <h4 class="mb-0" id="flask">Flask</h4>
                </blockquote>
                <p>Flask is a microservice, “micro” in microframework means Flask aims to keep the core simple but extensible. Flask won’t make many decisions for you, such as what database to use. Those decisions that it does make, such as what templating engine to use, are easy to change. Everything else is up to you, so that Flask can be everything you need and nothing you don’t.
                </p>
                <p>
                  By default, Flask does not include a database abstraction layer, form validation or anything else where different libraries already exist that can handle that. Instead, Flask supports extensions to add such functionality to your application as if it was implemented in Flask itself. Numerous extensions provide database integration, form validation, upload handling, various open authentication technologies, and more. Flask may be “micro”, but it’s ready for production use on a variety of needs.
                </p>
                <blockquote class="blockquoteb text-primary">
                  <h4 class="mb-0" id="database">Database schema design</h4>
                </blockquote>
                <p>
                  <p><iframe width="560" height="315" src='https://dbdiagram.io/embed/619da3d602cf5d186b65421c'> </iframe></p>
                  <p>Postgres and Redis.</p>           
                  Our app uses Postgres in the backend to store all users related data and Redis for the celery tasks.
                </p>
                <blockquote class="blockquoteb text-primary">
                  <h4 class="mb-0" id="docker">Docker and Docker-compose</h4>
                </blockquote>
                <p> Why use docker?</p>
                <p>
                  docker is an awesome tool that let's you package your application into containers... All those containers can then be ran together using docker-compose. 
                </p>
                <p>docker-compose.yml</p>
                  <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/docker_compose.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/docker_compose1.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <br>
                <p>Dockerfile</p>
                  <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/dockerfile.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <br>
                <blockquote class="blockquoteb text-primary">
                  <h4 class="mb-0" id="extensions">Flask extensions</h4>
                </blockquote>
                <p>
                  Using flask stable and trusted extensions we can make your app development much quicker. for instance we use flask-login extension for user to log in and out the application. if we wanted to implement a secure user authentication model from sracth it would have been a lot of extra work. We also use two other extensions: flask_mail for email management and flask_debug_toolbar for debugging in development.
                </p>
                <blockquote class="blockquoteb text-primary">
                  <h4 class="mb-0" id="linode">Linode server configuration</h4>
                </blockquote>
                <p>we also have another dockerfile for the Nginx and conf that will be saved in the /etc/nginx/conf.d/default.conf folder on the server side.
                </p>
                <p>Dockerfile</p>
                  <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/dockerfile_nginx.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <br>
                <p>conf</p>
                  <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/conf.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <br>
                <p>
                  On the server side we have a debian 9 distribution with docker installed on it. We then go to the /var folder which will be our working directory.
                  We use Nginx as a proxy server. Nginx can handle many request at the same time and is highluy scalable. which is why we made that choice. it will communicate to our server and return all requests.
                  <p>cd /<p>
                  <p>cd /var</p>
                  <p>mkdir app</p>
                  <p>cd app</p>
                  we can then pull our app repository from Github by running this command:
                  <p>git pull "app repository link"</p>
                  <p>Now, we need to complete a few more steps before we can have our server up and running the app securely. 
                  UFW, or Uncomplicated Firewall, is an interface to iptables that is geared towards simplifying the process of configuring a firewall. While iptables is a solid and flexible tool, it can be difficult for beginners to learn how to use, to properly configure a firewall. If you’re looking to get started securing your network, and you’re not sure which tool to use, UFW may be the right choice for you. We can download it using this command below:</p>
                  <p>sudo apt install ufw</p>
                  <p>ufw should be correctly installed on the server. To allow certain port we run this command:</p>
                  <p>sudo ufw allow "port or service"</p>
                  <p>sudo ufw allow ssh (to allow ssh connection for instance).</p>
                  <p>If we want to check the status of the firewall we can run:</p>
                    <div class="col">
                        <div class="about-img">
                          <img src="{{ url_for('static', filename='img/ufw.jpg')}}" class="img-fluid rounded b-shadow-a" alt="">
                        </div>
                  </div>
                  <br>
                  We still have more features we can add such as setting up https with ssl certificate and so on, but our app is now launched on the server with an IP address.
                </p>
              </div>
            </div>
          
    </section><!-- End Blog Single Section -->

  </main>

  <!-- ======= Footer ======= -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="copyright-box">
            <p class="copyright">&copy; Copyright <strong>Malick Gueye</strong>. All Rights Reserved</p>    
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->


  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/jquery.easing/jquery.easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/waypoints/jquery.waypoints.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/counterup/jquery.counterup.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/owl.carousel/owl.carousel.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/typed.js/typed.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/venobox/venobox.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

</html>